# react-scripts 1.x uses spdy/http-deceiver, which requires Node's legacy HTTP parser.
FROM node:16.20.2-alpine
WORKDIR /app
COPY ./package.json ./
RUN npm install
COPY . .
CMD ["npm", "run", "start"]
