version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres_password}
  redis:
    image: "redis:latest"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "8080:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_TLS=${REDIS_TLS:-false}
      - PGUSER=${PGUSER:-postgres}
      - PGHOST=${PGHOST:-postgres}
      - PGDATABASE=${PGDATABASE:-postgres}
      - PGPASSWORD=${PGPASSWORD:-postgres_password}
      - PGPORT=${PGPORT:-5432}
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_TLS=${REDIS_TLS:-false}
